name: Build docker image for minio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    defaults:
      run:
        working-directory: './'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build'
        run: |
          docker build . --tag ghcr.io/yakubique/minio-ci:v1
          docker push ghcr.io/yakubique/minio-ci:v1

  build-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: opaoz
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        run: |
          docker buildx build --platform linux/amd64,linux/arm64  -q --push . -t opaoz/minio-ci:v1
